CSharp Web 2018/Csharp MVC Frameworks - ASP.NET Core/Exercise Middleware and filters/Eventures/Eventures.Web/Controllers/Accounts/AccountsController.cs
namespace Eventures.Web.Controllers.Accounts
{
    using AutoMapper;
    using Eventures.Models;
    using Eventures.Services.Accounts.Contracts;
    using Eventures.Web.ViewModels.Accounts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using System.Threading.Tasks;

    public class AccountsController : BaseController
    {
        private readonly IMapper mapper;
        private readonly IAccountService accountsService;
        private readonly SignInManager<EventureUser> signInManager;

        public AccountsController(IMapper mapper, IAccountService accountsService, SignInManager<EventureUser> signInManager)
        {
            this.mapper = mapper;
            this.accountsService = accountsService;
            this.signInManager = signInManager;
        }

        public IActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserInputModel model)
        {
            var user = this.mapper.Map<EventureUser>(model);

            if (ModelState.IsValid)
            {
                var result = this.accountsService.Login(user, model.Password);

                if (result == true)
                {
                    return this.Redirect("/");
                }
                else
                {
                    return this.View(model);
                }
            }
            else
            {
                return this.View(model);
            }
        }

        public IActionResult Register()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Register(RegisterUserViewModel model)
        {
            var user = this.mapper.Map<EventureUser>(model);

            if (ModelState.IsValid)
            {
                var result = this.accountsService.Register(user, model.Password);

                if (result == true)
                {
                    return this.Redirect("/");
                }
                else
                {
                    return this.View(model);
                }
            }
            else
            {
                return this.View(model);
            }
        }

        public IActionResult Logout()
        {
            this.accountsService.Logout();
            return this.Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.RouteUrl("SigninFacebook", new { returnUrl });
            var properties = signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);

            var test = this.Request;

            var result = this.Challenge(properties, provider);
            return result;
        }

        [HttpGet("signin-facebook", Name = "SigninFacebook")]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            await this.accountsService.ExternalLogin();

            return this.Redirect("/");
        }

        [Authorize("Admin")]
        public IActionResult EditRoles(string currentUser)
        {
            var users =
                this.accountsService
                .GetUsersWithRoles(this.User.Identity.Name)
                .Select(u => new EditUserRoleViewModel
                {
                    Role = u.Value,
                    Username = u.Key.UserName,
                    UserId = u.Key.Id
                })
                .ToArray();

            return this.View(users);
        }

        [Authorize("Admin")]
        public IActionResult Promote(string id)
        {
            this.accountsService.Promote(id);
            return this.Redirect("/Accounts/EditRoles");
        }

        [Authorize("Admin")]    
        public IActionResult Demote(string id)
        {
            this.accountsService.Demote(id);
            return this.Redirect("/Accounts/EditRoles");
        }
    }
}

CSharp Web 2018/Csharp MVC Frameworks - ASP.NET Core/Exercise Middleware and filters/Eventures/Eventures.Web/Controllers/Events/EventsController.cs
namespace Eventures.Web.Controllers.Events
{
    using AutoMapper;
    using Eventures.Models;
    using Eventures.Services.Events.Contracts;
    using Eventures.Services.Orders.Contracts;
    using Eventures.Web.Filters;
    using Eventures.Web.ViewModels.Events;
    using Eventures.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using System.Linq;

    public class EventsController : BaseController
    {
        private readonly IOrdersService ordersService;
        private readonly IMapper mapper;
        private readonly IEventsService eventsService;
        private readonly ILogger<EventsController> logger;

        public EventsController(IOrdersService ordersService, IMapper mapper, IEventsService eventsService, ILogger<EventsController> logger)
        {
            this.ordersService = ordersService;
            this.mapper = mapper;
            this.eventsService = eventsService;
            this.logger = logger;
        }

        [Authorize("Admin")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [TypeFilter(typeof(LogEventFilter))]
        [Authorize("Admin")]
        public IActionResult Create(CreateEventInputModel model)
        {
            var eventuresEvent = this.mapper.Map<Event>(model);

            if (ModelState.IsValid)
            {
                this.eventsService.AddEvent(eventuresEvent, this.User);

                this.logger.LogInformation($"Event created: {model.Name}");
               
                return this.Redirect("/Events/All");
            }
            else
            {
                return this.View(model);
            }
        }

        public IActionResult All(int start)
        {
            var totalEventsCount = 
                this.eventsService
                .AllEventsCount();

            var events = 
                this.eventsService
                .EventsOnOnePage(start);

            var viewModel = new EventsOnPageViewModel
            {
                Events = events,
                Start = start,
                TotalEventsCount = totalEventsCount
            };
            
            return this.View(viewModel);
        }

        public IActionResult My()
        {
            var events = 
                this.eventsService
                .MyEvents(this.User);

            var mappedEvents =
                events
                .Select(e => this.mapper.Map<MyEventsViewModel>(e))
                .ToArray();

            return this.View(mappedEvents);
        }

        [HttpPost]
        public IActionResult All(OrderInputModel model, int start)
        {
            if (ModelState.IsValid)
            {
                this.ordersService.AddOrder(model.TicketsCount, this.User, model.EventName);

                return this.Redirect("/");
            }
            else
            {
                var totalEventsCount =
                    this.eventsService
                    .AllEventsCount();

                var events = 
                    this.eventsService
                    .EventsOnOnePage(start);

                var viewModel = new EventsOnPageViewModel
                {
                    Events = events,
                    Start = start,
                    TotalEventsCount = totalEventsCount
                };

                return this.View(viewModel);
            }
        }
    }
}

CSharp Web 2018/Csharp MVC Frameworks - ASP.NET Core/Exercise Middleware and filters/Eventures/Eventures.Web/Controllers/Orders/OrdersController.cs
namespace Eventures.Web.Controllers.Orders
{
    using AutoMapper;
    using Eventures.Services.Orders.Contracts;
    using Eventures.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Linq;

    [Authorize]
    public class OrdersController : BaseController
    {
        private readonly IMapper mapper;
        private readonly IOrdersService ordersService;

        public OrdersController(IMapper mapper, IOrdersService ordersService)
        {
            this.mapper = mapper;
            this.ordersService = ordersService;
        }

        [Authorize("Admin")]
        public IActionResult All()
        {
            var orders = this.ordersService.GetAllOrders();
            //Finish
            var mappedOrders =
                orders
                .Select(o =>
                        this.mapper
                        .Map<OrderViewModel>(o))
                .ToArray();

            this.mapper.Map<OrderViewModel[]>(orders);

            return this.View(mappedOrders);
        }
    }
}

CSharp Web 2018/Csharp MVC Frameworks - ASP.NET Core/Exercise Middleware and filters/Eventures/Eventures.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eventures</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-fixed-top bg-eventure">
        <div class="container">
            <div class="navbar-header">
                <button type="button" style="background-color:black;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" style="font-size:20px" asp-action="Index">Eventures</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events</a>
                            <ul class="dropdown-menu p-0">
                                <li>
                                    <ul class="list-inline">
                                        <li class="p-0" >
                                            <a class="dropdown-item" asp-controller="Events" asp-action="All">All Events</a>
                                            <a class="dropdown-item"asp-controller="Events" asp-action="My">My Events</a>
                                        </li>
                                        @if (this.User.IsInRole("Admin"))
                                        {
                                            <li class="p-0">
                                                <a class="dropdown-item" asp-controller="Events" asp-action="Create">Create Event</a>
                                            </li>
                                        }
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Orders</a>
                                <ul class="dropdown-menu p-0">
                                    <li>
                                        <ul class="list-inline p-0">
                                            <li>
                                                <a class="dropdown-item" asp-controller="Orders" asp-action="All">All Orders</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin</a>
                                <ul class="dropdown-menu p-0">
                                    <li>
                                        <ul class="list-inline">
                                            <li>
                                                <a class="dropdown-item" asp-controller="Accounts" asp-action="EditRoles">Edit Roles</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    @RenderBody()

    <footer class="bg-eventure">
        <p>&copy; CopyRight Eventures Inc. 2018-2018. All Rights Reserved.</p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>